CREATE TABLE users (
    id int8 GENERATED BY DEFAULT AS IDENTITY,
    active boolean NOT NULL,
    first_name varchar(255),
    last_name varchar(255),
    password varchar(255),
    username varchar(255),
    PRIMARY KEY (id));

ALTER TABLE IF EXISTS users ADD CONSTRAINT constraint_username UNIQUE (username);

CREATE TABLE user_role (
    user_id int8 NOT NULL,
    roles varchar(255));

ALTER TABLE IF EXISTS user_role ADD CONSTRAINT
    user_role_pk FOREIGN KEY (user_id) REFERENCES users;

CREATE TABLE vacancies (
    vacancy_id int8 GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp,
    updated_at timestamp,
    description varchar(2048),
    requirements varchar(255),
    title varchar(255),
    user_id int8,
    PRIMARY KEY (vacancy_id));

CREATE TABLE candidate (
    id int8 GENERATED BY DEFAULT AS IDENTITY,
    degree varchar(255),
    department varchar(255),
    discord varchar(255),
    email varchar(255),
    first_name varchar(255),
    last_name varchar(255),
    phone_number varchar(255),
    years_of_experience varchar(255),
    vacancy_id int8,
    PRIMARY KEY (id));

ALTER TABLE IF EXISTS candidate ADD CONSTRAINT
    vacancy_id_pk FOREIGN KEY (vacancy_id) REFERENCES vacancies;

ALTER TABLE IF EXISTS vacancies ADD CONSTRAINT
    user_id_pk FOREIGN KEY (user_id) REFERENCES users;

CREATE TABLE vacancy_competencies (
    vacancy_id int8 NOT NULL, competencies varchar(255));

ALTER TABLE IF EXISTS vacancy_competencies ADD CONSTRAINT
    vacancy_competencies_pk FOREIGN KEY (vacancy_id) REFERENCES vacancies;